version: '2'

services:
  nginx:
    image: 'bitnami/nginx:1.16'
    ports:
      - '80:8080'
    volumes:
    - C:\Users\AlumnoM\Docker certs\certs
    - C:\Users\AlumnoM\Docker certs\my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
